# Database configuration
spring.datasource.url=jdbc:postgresql://aws-1-us-east-1.pooler.supabase.com:5432/postgres?sslmode=require
spring.datasource.username=postgres.dmkuwlcsnunlraisxrsu
spring.datasource.password=tg-j_VGk@uq6LLi
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# JWT secret key
security.jwt.secret-key =58abc832-d67b-4e0a-b673-bbdad4f761ab
security.jwt.expiration-time=3600000
#
# Mail properties
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${SUPPORT_EMAIL}
spring.mail.password=${APP_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

#spring.config.import=optional:file:.env[.properties]
